---
scenario:
  name: win2008r2
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: vagrant-win2008r2
    box: jborean93/WindowsServer2008R2
    provider_raw_config_args:  # 2020-09-25: without this option, Windows reboots indefinitely
      - "customize ['modifyvm', :id, '--graphicscontroller', 'vboxsvga']"
provisioner:
  name: ansible
  inventory:
    host_vars:
      vagrant-win2008r2:
        ansible_user: vagrant
        ansible_password: vagrant
        ansible_port: 55986
        ansible_host: 127.0.0.1
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_scheme: https
        ansible_winrm_server_cert_validation: ignore
verifier:
  name: ansible
